on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      with:
        webhook_url: https://discord.com/api/webhooks/1238439249515384852/kuNae6ZiohUV7GE0WQfi1VLNbRev-jnsnylpEAcFF_ftNoYx2TvxrfblJ-OAU0_8x_Op
        data: '{\"content\": \"Hello From GH Actions!\"}'
