name: test
on: 
  workflow_dispatch:
  
jobs:
 check-bats-version:
   runs-on: ubuntu-latest
   steps:
     - run: |
         curl --location --request POST 'https://discord.com/api/webhooks/1238439249515384852/kuNae6ZiohUV7GE0WQfi1VLNbRev-jnsnylpEAcFF_ftNoYx2TvxrfblJ-OAU0_8x_Op' \
           --header 'Accept: application/json' \
           --header 'Content-Type: application/json' \
           --data '{\"content\": \"Hello From GH Actions!\"}'
